apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: healthcare
data:
  FRONTEND_URL: "https://healthcare-project-six.vercel.app"
  AUTH_SERVICE_URL: "http://auth-service:3009"
  PATIENT_SERVICE_URL: "http://patient-service:3001"
  DOCTOR_SERVICE_URL: "http://doctor-service:3002"
  ADMIN_SERVICE_URL: "http://admin-service:3003"
  APPOINTMENT_SERVICE_URL: "http://appointment-service:3004"
  NOTIFICATION_SERVICE_URL: "http://notification-service:3005"
  TELEMEDICINE_SERVICE_URL: "http://telemedicine-service:3006"
  AI_SERVICE_URL: "http://ai-service:3007"
  PAYMENT_SERVICE_URL: "http://payment-service:3008"
